# .circleci/config.yml
version: 2

jobs:
  run-tests: 
    macos:
        xcode: "9.3.0"
    shell: /bin/bash --login -eo pipefail
    working_directory: /Users/distiller/project
    environment: 
        FL_OUTPUT_DIR: output
        REFRESH_CERTIFICATES: false
        SCAN_DEVICE: iPhone 5s
        SCAN_SCHEME: EZSource-Example
        SCAN_WORKSPACE: Example/EZSource.xcworkspace    
    steps:
      - run:
          name: Set Ruby Version
          command:  echo "ruby-2.4" > ~/.ruby-version
      - run: gem install bundler
      - run: gem update fastlane
      - checkout
      - run: bundle install
      - run: 
          name: Running Tests
          command: bundle exec fastlane runTests
      - store_artifacts:
          path: output
      - store_test_results:
          path: output/scan

workflows:
  version: 2
  build: 
    jobs:  
      - run-tests



