# .circleci/config.yml
version: 2

jobs:
  run-tests: 
    macos:
        xcode: "10.2.1"
    shell: /bin/bash --login -eo pipefail
    working_directory: /Users/distiller/project
    environment: 
        FL_OUTPUT_DIR: output
        REFRESH_CERTIFICATES: false
        SCAN_DEVICE: iPhone 5s
        SCAN_SCHEME: EZSource-Example
        SCAN_WORKSPACE: Example/EZSource.xcworkspace    
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-gems-{{ checksum "Gemfile.lock" }}
          # Fall back to using the latest cache if no exact match is found.
          - v1-gems-
      # Install gems.
      - run:
          name: Bundle install
          command: bundle check || bundle install
          environment:
            BUNDLE_JOBS: 4
            BUNDLE_RETRY: 3
      - save_cache:
          key: v1-gems-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run: 
          name: Running Tests
          command: bundle exec fastlane runTests
      - store_artifacts:
          path: output
      - store_test_results:
          path: output/scan

workflows:
  version: 2
  build: 
    jobs:  
      - run-tests



