# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  before_all do
    setup_circle_ci
  end


  desc "Setup CIRCLE"  
  lane :initialize do
   setup_circle_ci
  end 


  desc "Runs all the tests"
  lane :runTests do
    run_tests
  end

  lane :release_current do
    version = version_get_podspec(path: @podspec_name)
    if git_tag_exists(tag: version)
    UI.user_error!("The tag #{version} already exists on the repo. To release a new version of the library bump the version on #{@podspec_name}")
    end
    pod_lib_lint
    add_git_tag(tag: "#{version}")
    push_git_tags
    pod_push
 end

#Ending platform :ios do
end



